### ISSUE TITLE
Purpose and status?

### ISSUE THREAD

**Issue by paulrouget** [WebKitForWindows/docker-webkit-dev#35]
I stumbled into that project as I was looking at instructions on how to build Webkit for Windows.

- How is this project related to webkit.org? Is it a personal project?
- How does it compare to https://webkit.org/building-webkit-on-windows/ ? Is it a set of scripts/wrappers to make building webkit easier on Windows?
- If I wanted to build a production-ready version of Webkit for Windows, would you recommend to use this project?

Thanks :)

**Comment by donny-dont** [comment]
Hi @paulrouget this org is for the WinCairo port of WebKit. Currently Sony is running that port and all the org members here are employees of Sony Interactive Entertainment.

The docker containers here have all the tools for building WebKit for Windows. The `webkitdev/msbuild` is enough for you to download and build locally. It contains Visual Studio 2019 Build Tools, as well as LLVM. It also comes with all the tools required, `cmake`, `ninja` etc, and all the programming language support, `python`, `perl`, `ruby`, that is required to build WebKit. We also provide images that work with https://build.webkit.org and https://ews-build.webkit.org and run our bots off of those.

If you're comfortable with Docker on windows its definitely a way to easily run a development environment. You can also just copy out the `C:/tools` directory which has all the tools in one location and modify your path appropriately, install Visual Studio and you're good to go.

If you're interested in using it I can take a bit of time to make sure that the documentation is all up to date with everything. Just let me know.

**Comment by fujii** [comment]
There is no production-ready Webkit Windows ports at the moment. I hope [this article](https://fujii.github.io/2019/07/05/webkit-on-windows/) would help you choose the best Windows port for your use case. I'd like to recommend to use Chocolatey to setup a building env. See [WinCairo doc](https://trac.webkit.org/wiki/BuildingCairoOnWindows).

**Comment by paulrouget** [comment]
@donny-dont Thank you. That's useful. Just exploring options for now. I will definitively look at this docker image if I end building webkit on Windows.

@fujii that article answered some questions I had. Thank you.
