### ISSUE TITLE
Update fonts based on LayoutTests needs

### ISSUE THREAD

**Issue by rkirsling** [WebKitForWindows/docker-webkit-dev#6]
107 layout tests fail on the bots due to missing fonts in the `windowsservercore` image.

If the fonts can be acquired from the host machine, then we can fix this as follows.

fonts.reg:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts]
"Lucida Sans Unicode (TrueType)"="l_10646.ttf"
"Microsoft Sans Serif (TrueType)"="micross.ttf"
"MS Gothic & MS UI Gothic & MS PGothic (TrueType)"="msgothic.ttc"
"Papyrus (TrueType)"="PAPYRUS.TTF"
"Tahoma (TrueType)"="tahoma.ttf"
```

Dockerfile:
```
FROM webkitdev/msbuild

COPY l_10646.ttf C:/Windows/Fonts
COPY micross.ttf C:/Windows/Fonts
COPY msgothic.ttc C:/Windows/Fonts
COPY PAPYRUS.TTF C:/Windows/Fonts
COPY tahoma.ttf C:/Windows/Fonts
COPY fonts.reg C:/

RUN reg import C:/fonts.reg
```

**Comment by donny-dont** [comment]
I'm not totally sure how we can distribute these. My hope is that the new windows images will have these contained in there.

**Comment by rkirsling** [comment]
It was suggested that `windowsservercore` intentionally omits them:
https://twitter.com/Taylorb_msft/status/1035044867255267328

**Comment by donny-dont** [comment]
Right so he's saying they would be at https://hub.docker.com/r/microsoft/windows/ since there's now a windows image. Currently that requires Windows Server 2019 or Windows 1809.

I think with the testing bots well end up using the windows image for that.

**Comment by donny-dont** [comment]
In https://github.com/WebKitForWindows/docker-webkit-dev/commit/b2691010b419a930a334adca55ed3dd8bd4852c8 I added an image based on the `windows` image discussed in the tweet. If that particular image is used this issue goes away.
